version: '3.3'

## tomcat.war -> backend must call .war file tomcat.war file, so it works

services:
    db:
      image: postgres:14
      ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=USER123
            - POSTGRES_DB=backend
        volumes: 
            - db-data:/var/lib/postgresql/data/
        restart: always
    web:
      image: tomcat:9.0.41-jdk11
      ports:
            - "80:8080"
      environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
            - SPRING_DATASOURCE_USERNAME=user
            - SPRING_DATASOURCE_PASSWORD=USER123
      volume:
            - ./tomcat.war:/usr/local/tomcat/webapps/tomcat.war
      restart: always
    
volumes:
  db-data: